### ISSUE TITLE
Data overriding through plan is not working as expected

### ISSUE THREAD

**Issue by pvpurohit** [nexiality/nexial-core#13]
### Subject of the issue
Data overriding through plan is not working as expected

### Your environment Details

* Nexial Version: nexial-core-v3.2_0872
* Java(jdk) Version: jdk1.8.0_181
* Operating System: Windows10
* Browser Version (if applicable): Chrome 84.0.4147.105

### Steps to reproduce

 - Step: Create Plan as below:

description | test script | test scenarios | test data | data sheets | fail fast? | wait? | load test?
-- | -- | -- | -- | -- | -- | -- | --
Run It1 | FirstProj.xlsx | runIterationToFile | FirstProj.data.xlsx | runIterationToFile | no | yes | no
Run It2 | FirstProj.xlsx | runIterationToFile | FirstProj.data.xlsx | runIterationToFile,second_iteration | no | yes | no

Where in step 2 - the datasheet second_iteration overrides the runIterationToFile datasheet.

 - Step2: Create datasheet as attached
[FirstProj.data.xlsx](https://github.com/nexiality/nexial-core/files/4999850/FirstProj.data.xlsx)
 
Functionality :
open web url
search Nexial Automation
search Nexial Core

Data sheet will have two datasheets
Datasheet1 has below variables and values
nexial.scope.iteration=1
search_term - 2 values in column B and C (Nexial Automation, Nexial Core)
Datasheet2 has below variables and values
nexial.scope.fallbackToPrevious = true
nexial.scope.iteration=2

-Step3: Execute the plan

### Expected behavior

In this case below execution is expected:
Step 1 - during execution of step1 from plan, nexial should first search the term "Nexial Automation"
Step 2 - during execution of step2 from plan, the nexial.scope.iteration variable value in runIterationToFile datasheet should be overwritten by the value in second_iteration datasheet and hence nexial  should search the term "Nexial Core"

### Actual behaviour

During execution only "Nexial Automation" term is getting searched twice, data is not overwritten

### Attach Logs

[nexial-20200730_131111.2020-07-30.log](https://github.com/nexiality/nexial-core/files/4999820/nexial-20200730_131111.2020-07-30.log)

**Comment by mikeliucc** [comment]
Perhaps I didn't understand the issue completely... I created my own example, and was able to execute the plan as expected.

Here's the plan:
![image](https://user-images.githubusercontent.com/8107782/89254754-c863fb00-d5d4-11ea-90b9-0eaad9dfc975.png)

I have 3 steps here to show a variety of confirmation that the data loading logic is working as expected. My intention is show that Nexial can:
1. load data from a single data sheet (Plan Step 1).
2. load data from multiple data sheets, with the latter overriding the former (Plan Step 2).
3. load data from multiple data sheets, with the latter overriding only the iteration configuration (Plan Step 3).

My data file is pretty simple:
`#default`:
![image](https://user-images.githubusercontent.com/8107782/89255114-c0588b00-d5d5-11ea-8ee8-e4df4c8792f3.png)

`Scenario1`:
![image](https://user-images.githubusercontent.com/8107782/89255129-cb132000-d5d5-11ea-9be7-61cab25f4b71.png)

`Scenario2`:
![image](https://user-images.githubusercontent.com/8107782/89255144-d5351e80-d5d5-11ea-8c63-ec6dc495bdc9.png)

`Scenario3`:
![image](https://user-images.githubusercontent.com/8107782/89255159-debe8680-d5d5-11ea-88a0-14c04e7b54a8.png)

The script simply sums up the numbers and assert totals against `${expected-sum}`:
![image](https://user-images.githubusercontent.com/8107782/89255242-175e6000-d5d6-11ea-8410-6d021e08485b.png)

I added a few flow control and a pause at the end so that I can examine the output as the execution goes along. Even without looking at the progress of the execution, one can reply on the first step `base >> verbose()` to see that the data is loaded correctly. Here are the snippets of the log file:

#### Plan Step 1, Iteration 1
![image](https://user-images.githubusercontent.com/8107782/89255417-85a32280-d5d6-11ea-9392-d8ea57669b38.png)

#### Plan Step 1, Iteration 2
![image](https://user-images.githubusercontent.com/8107782/89255440-9784c580-d5d6-11ea-963b-3bb6b3c3efec.png)

#### Plan Step 1, Iteration 3
![image](https://user-images.githubusercontent.com/8107782/89255466-a8353b80-d5d6-11ea-9602-b099a39a6976.png)

#### Plan Step 2, Iteration 1 (iteration id = 2)
![image](https://user-images.githubusercontent.com/8107782/89255502-bdaa6580-d5d6-11ea-8406-8aa0dc54121f.png)

#### Plan Step 2, Iteration 2 (iteration id = 3)
![image](https://user-images.githubusercontent.com/8107782/89255547-db77ca80-d5d6-11ea-97a9-59b55c802b0d.png)

#### Plan Step 2, Iteration 3 (iteration id = 4)
![image](https://user-images.githubusercontent.com/8107782/89255579-ec284080-d5d6-11ea-9842-8ee5aad02e8e.png)

#### Plan Step 3, Iteration 1 (iteration id = 2)
![image](https://user-images.githubusercontent.com/8107782/89255596-f5b1a880-d5d6-11ea-9419-468d47409a55.png)

#### Plan Step 3, Iteration 2 (iteration id = 3)
![image](https://user-images.githubusercontent.com/8107782/89255629-0eba5980-d5d7-11ea-9394-9bb2542bda0a.png)

#### Plan Step 3, Iteration 3 (iteration id = 5)
![image](https://user-images.githubusercontent.com/8107782/89255649-1a0d8500-d5d7-11ea-8006-f2bfae9d13bf.png)

I'm attaching my example project and log file here for your reference:
[SampleWorkingExample.zip](https://github.com/nexiality/nexial-core/files/5020223/SampleWorkingExample.zip)
[nexial-20200803_214927.2020-08-03.log](https://github.com/nexiality/nexial-core/files/5020225/nexial-20200803_214927.2020-08-03.log)

Would you mind giving this a try from your environment?

**Comment by mikeliucc** [comment]
OK.. found the issue -- turns out that when the latter datasheet specifies an iteration of a higher number than that of a previously loaded datasheet, Nexial then resorts to using only the iteration data that was previously loaded. As such iteration data outside the specified iteration(s) of the previously datasheet was not subsequently available.

Good catch!

Code fixes have been implemented. Please give it a try with build #884 (or later). Thanks for reporting this!

automike

**Comment by pvpurohit** [comment]
The fixes worked as expected. Thank You Mike for the quick build.
