### ISSUE TITLE
Could not find or load main class org.nexial.core.tools.SeleniumScriptConverter while converting selenium code to nexial.

### ISSUE THREAD

**Issue by vikramAccion** [nexiality/nexial-core#3]
Hi, I am facing issue while converting selenium .java file to nexial using selenium2nexial.cmd <file_name.java> command.

getting following error message.

![selenium2nexial](https://user-images.githubusercontent.com/38977075/39621844-c45436a6-4fad-11e8-9101-eb20080c2cff.jpg)

Looks like org.nexial.core.tools.SeleniumScriptConverter is missing in nexial-core-1.1_0027.jar

![selenium2nexial_2](https://user-images.githubusercontent.com/38977075/39622074-8f267858-4fae-11e8-9c2b-2ecb8c697e23.jpg)

Could you please help me out with this issue. Thanks in advance.

**Comment by mikeliucc** [comment]
Hi @vikramAccion,

The `selenium2nexial.cmd` isn't ready for use, and that's why there isn't any documentation for it as of yet.  This isn't a top priority for us at the moment, but we could possibly adjust accordingly if there's interest/urgency for it.

However, I should be clear that this utility script isn't designed to convert Selenium java code into Nexial script.  Instead, it aims to perform a one-way conversion of the the test cases (HTML) generated through [Selenium IDE](https://www.seleniumhq.org/docs/02_selenium_ide.jsp) into a new Nexial script.  Based on your comment above, it doesn't look like this is what you are looking for.  Please confirm.

At this time, this script would be complete at the earliest by v1.2, which would likely be the beginning of June.

Hope this helps to clarify... Thanks!

**Comment by vikramAccion** [comment]
Hi Mike, Thanks for quick reply. It was helpful.
