### ISSUE TITLE
Request for JSON expression to ability to add data to JSON structure

### ISSUE THREAD

**Issue by jwetter** [nexiality/nexial-core#4]
**Is your feature request related to a problem? Please describe.**
I am needing to create a list of variables for verification and due to JSON being very understandable, have JSON being the structure used in the tests being written.  The downside to this is that creating the JSON object requires manual Save / Append of text data in the proper structured format.  This makes dynamically adding data difficult when it comes from multiple previous tests or a macro to be verified in test.

**Describe the solution you'd like**
Under JSON expression would like there to be a way to add new JSON Data to both new/existing objects and arrays.

**Describe alternatives you've considered**
Manual creation of the JSON data in a variable and separate variables for all elements being tested.

**Comment by mikeliucc** [comment]
Thanks @jwetter for the great suggestion! Working on it....

**Comment by mikeliucc** [comment]
@jwetter the requested feature is available now (since Build #0126). Please refer to https://nexiality.github.io/documentation/commands/json/addOrReplace(json,jsonpath,input,var) for documentation and examples. The implementation might be a bit of overkill for your specific scenario but we wanted this feature to work in a more generalized context (which is also why it took a bit more time than previously estimated).

Please give it a try and let us know how it works out. If this new command does the job, please kindly close this issue.

Thanks!
